### ISSUE TITLE
Ardwen's clothes + Stone Wall bug

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-game#802] opened 2019-02-07 20:46 UTC
If you get power Stone Wall, and put Ardwen's gloves at the same time, the HP stats start to be buggy. If you hover it, it's "blurry" between the two possible values (apply increase because of artifact or not), like changing the value and then back again multiple times per second. If you open hero information, it's "blurry" (changing all the time) as well.

**Comment by dorkster** [comment] 2019-02-07 21:13
Which version of Flare are you using? I believe this bug was already found and fixed in a recent version.

**Comment by vgaming** [comment] 2019-02-07 21:36
UPD: not sure why, but bug disappeared by itself. The HP is "constant" now.

**Comment by vgaming** [comment] 2019-02-07 21:38
@dorkster `Flare 1.09.04` built from 8d02acb8a42cb9842ee8e24e07a066e31dead1d7 I think.  (engine 46ba69ed553197bb60b224b47aaa78a13f3659cd)

**Comment by vgaming** [comment] 2019-02-07 21:42
By the way, unrelated, but I wonder if the absorb bonus works correctly. With those gloves, I get +25 HP, +4 absorb minimum and +5 absorb maximum. The difference between min and max starts to be 2 when I put the gloves on, but is 1 without the gloves (for my hero).
Is that intended behavior?

**Comment by dorkster** [comment] 2019-02-07 21:53
Okay, that version is recent enough to not be the particular bug I was talking about. I can't reproduce, but I guess it's good that it worked itself out for you.

>By the way, unrelated, but I wonder if the absorb bonus works correctly. With those gloves, I get +25 HP, +4 absorb minimum and +5 absorb maximum. The difference between min and max starts to be 2 when I put the gloves on, but is 1 without the gloves (for my hero).
Is that intended behavior?

Sounds correct to me. The gloves have a base +1 min absorb and +2 max absorb. Then the bonus point in Stone Wall can grant +3 to min/max absorb. So combine the two sources and you get +4 min / +5 max.

**Comment by vgaming** [comment] 2019-02-07 22:01
oh, indeed -- I forgot about "direct" absorbtion of the gloves. Thanks for the explanation.

Regarding the bug: I observed it the first time I got the gloves, right after putting them on the first time. Can't repro anymore, unfortunately.

**Comment by dorkster** [comment] 2019-03-10 21:45
Thanks to [some help](https://opengameart.org/forumtopic/bug-ardwens-gloves-stone-wall) on the forums, I've been able to track down the problem here.

Let's say the player has one point invested in Stone Wall and equips the gloves (Stone Wall 1 +1). The game was checking the usage requirements of Stone Wall 2, which requires player level 3. So the "flickering" would occur if the player was below level 3, and the issue would disappear once they reached level 3.

The intended behavior is to only check the requirements of the unlocked power without any bonus points. [A fix has been pushed](https://github.com/flareteam/flare-engine/commit/890a7b9dd312ebcdd3a645dd70933e3f45c41920).

**Closed by dorkster** 2019-03-10 21:45 UTC
Labels: bug, engine

**Comment by vgaming** [comment] 2019-03-11 12:51
Thanks! Awesome!

There's information for me as well: I could've just provide the savefile. Not sure I had it, but probably I did (I do occasional save-s).
